CREATE TABLE lion_ip(
  id CHAR(32) NOT NULL PRIMARY KEY ,
  time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lion_ip_detail(
  id CHAR(32) NOT NULL PRIMARY KEY ,
  ip_id CHAR(32) NOT NULL ,
  parent VARCHAR(128) NOT NULL ,
  children VARCHAR(1024),
  src VARCHAR(16)
);